[package]
name = "multiuploader"
version = "0.1.0"
authors = ["sipu"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "multiuploader"
path = "src/main.rs"

[dependencies]
actix-web = "4.5.1"
actix-multipart = "0.6.1"
actix-files = "0.6.5"
serde="1.0.197"
serde_json = "1.0.114"
serde_derive="1.0.197"
derive_more = "0.99.17"
uuid = { version = "1.7.0",  features = ["v4"] }
futures-util = { version = "0.3.30", default-features = false, features = ["std"] }
